spring.application.name=Url-Shorterner-Springboot
spring.datasource.url=jdbc:mysql://localhost:3306/urlshorterner
spring.datasource.username=root
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect